version: '3.1'
services:

  moviebuffs-hub:
    image: sivaprasadreddy/moviebuffs
    container_name: moviebuffs-hub
    environment:
      - SPRING_PROFILES_ACTIVE=default
    ports:
      - "18080:8080"
      - "18787:8787"
    restart: always
